<a href="https://colab.research.google.com/github/Hajar-AC/data-science-python/blob/master/Lab2_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas
Pandas est le package de prédilection pour traiter des données structurées.

Pandas est basé sur 2 structures extrêmement liées les Series et le DataFrame.

Ces deux structures permettent de traiter des données sous forme de tableaux indexés.

Les classes de Pandas utilisent des classes de Numpy, il est donc possible d'utiliser les fonctions universelles de Numpy sur les objets Pandas.

In [38]:
# on importe pandas avec :
import pandas as pd
import numpy as np
%matplotlib inline

# Le DataFrame

- Les DataFrame sont des objets très souples pouvant être construits de différentes façon
- On peut les construire en récupérant des données copier / coller, où directement sur Internet, ou en entrant les valeurs manuellement


- Les DataFrame se rapprochent des dictionnaires et on peut construire ces objets en utilisant `DataFrame(dico)`
- De nombreux détails sur la création des DataFrame se trouve sur ce site :

<http://pandas.pydata.org/pandas-docs/dev/generated/pandas.DataFrame.html>

# Construction de DataFrame

On peut simplement construire un DataFrame avec le classe pd.DataFrame() à partir de différentes structures :

In [39]:
frame1=pd.DataFrame(np.random.randn(10).reshape(5,2),
             index=["obs_"+str(i) for i in range(5)],
             columns=["col_"+str(i) for i in range(2)])
frame1

          col_0     col_1
obs_0 -0.720291  0.335454
obs_1 -0.069611 -0.303179
obs_2 -0.522512 -0.337095
obs_3  0.669407  1.486870
obs_4  0.249212  0.449062

# Opérations sur les DataFrame

On peut afficher le nom des colonnes :

In [40]:
print(frame1.columns)

Index(['col_0', 'col_1'], dtype='object')

On peut accéder à une colonne avec :
- `frame1.col_0` : attention au cas de nom de colonnes avec des espaces...
- `frame1['col_0']`

On peut accéder à une cellule avec :
- `frame1.loc['obs1','col_0']` : on utilise les index et le nom des colonnes
- `frame1.iloc[1,0]` : on utilise les positions dans le DataFrame

# Options de visualisation et de résumé

Pour afficher les 3 premières lignes, on peut utiliser :

In [41]:
frame1.head(3)

          col_0     col_1
obs_0 -0.720291  0.335454
obs_1 -0.069611 -0.303179
obs_2 -0.522512 -0.337095

Pour afficher un résumé du DF :

In [42]:
frame1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, obs_0 to obs_4
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   col_0   5 non-null      float64
 1   col_1   5 non-null      float64
dtypes: float64(2)
memory usage: 292.0+ bytes

# Importer des données externes

Pandas est l'outil le plus efficace pour importer des données externes, il prend en charge de nombreux formats dont csv, Excel, SQL, SAS...


## Importation de données avec Pandas

Quel que soit le type de fichier, Pandas possède une fonction :
```python
frame=pd.read_...('chemin_du_fichier/nom_du_fichier',...)
```
Pour écrire un DataFrame dans un fichier, on utilise :
```python
frame.to_...('chemin_du_fichier/nom_du_fichier',...)
```

**Exercice :**
    
Importer un fichier `.csv` avec `pd.read_csv()`. On utilisera le fichier "./data/airbnb.csv"

In [43]:
airbnb = pd.read_csv("CAC40.csv")

In [44]:
# pour vérifier que vous avez bien répondu à l'exercice, soumettre cette cellule
# on utilise maj + Entrée
assert airbnb["Date"].dtype == object
print("Bien importé !")

Bien importé !

Importer un fichier `.csv` qui a comme séparateur `;`, le nom du fichier est `base-dpt.csv`

In [45]:
base_dpt = pd.read_csv("base.csv", sep = ';')

In [46]:
# pour vérifier que vous avez bien répondu à l'exercice, soumettre cette cellule
# on utilise maj + Entrée
assert type(base_dpt) == pd.DataFrame
print("Bien importé !")

Bien importé !

# D'autres types de données

## JSON
Les objets JSON ressemblent à des dictionnaires.

On utilise le module `json` puis la fonction `json.loads()` pour transformer une entrée JSON en objet json

## HTML
On utilise `pd.read_html(url)`. Cet fonction est basée sur les packages `beautifulsoup` et `html5lib`

Cette fonction renvoie une liste de DataFrame qui représentent tous les DataFrame de la page. On ira ensuite chercher l'élément qui nous intéresse avec `frame_list[0]`

**Exercice :**
    
Importez un tableau en html depuis la page https://www.fdic.gov/resources/resolutions/bank-failures/failed-bank-list/

In [47]:
web_bank = pd.read_html("https://www.fdic.gov/resources/resolutions/bank-failures/failed-bank-list/")

In [48]:
frame_bank = web_bank[0]

In [49]:
# pour vérifier que vous avez bien répondu à l'exercice, soumettre cette cellule
# on utilise maj + Entrée
assert type(frame_bank) == pd.DataFrame
print("Bien importé !")

Bien importé !

# Importer depuis Excel

On a deux approches pour Excel :
- On peut utiliser `pd.read_excel()`
- On peut utiliser la classe `pd.ExcelFile()`

Dans ce cas, on utilise :
```python
xlsfile=pd.ExcelFile('fichier.xlsx')
xlsfile.parse('Sheet1')
```

**Exercice :**
    
Importez un fichier Excel avec les deux approches, on utilisera : `credit2.xlsx` et `ville.xls`

1- avec `pd.read_excel()` pour le fichier `credit2.xlsx`

In [50]:
credit2 = pd.read_excel("credit2.xlsx")

In [56]:
# pour vérifier que vous avez bien répondu à l'exercice, soumettre cette cellule
# on utilise maj + Entrée
assert credit2["age"].max() == 103
#print(f"La valeur maximale de la colonne 'age' est : {credit2['age'].max()}")
print("Bravo !")

Bravo !

2- avec `pd.ExcelFile()` pour le fichier `ville.xls`

In [58]:
ville_excel = pd.ExcelFile("ville.xlsx")

In [59]:
ville_excel.sheet_names

['ville', 'ville-ain']

In [60]:
frame_ville = ville_excel.parse("ville")

In [61]:
# pour vérifier que vous avez bien répondu à l'exercice, soumettre cette cellule
# on utilise maj + Entrée
assert type(frame_ville) == pd.DataFrame
print("Bravo !")

Bravo !

# Importer des données SQL

Pandas possède une fonction `read_sql()` qui permet d’importer directement des bases de données ou des queries dans des DataFrame

Il faut tout de même un connecteur pour accéder aux bases de données

Pour mettre en place ce connecteur, on utlise le package SQLAlchemy.

Suivant le type de base de données, on utilisera différents codes mais la structure du code est toujours la même

In [62]:
# on importe l'outil de connexion
from sqlalchemy import create_engine

On crée une connexion
```python
connexion=create_engine("sqlite:///(...).sqlite")
```

On utlise une des fonctions de Pandas pour charger les données
```python
requete="""select ... from ..."""
frame_sql=pd.read_sql_query(requete,connexion)
```

**Exercices :**
    
Importez la base de données SQLite salaries et récupérez la table Salaries dans un DataFrame

*Indice :* On commence par créer la connexion et ensuite on fait la requête `select * from salaries`, la connexion se fait en utilisant l'adresse : "sqlite:///./data/salaries.sqlite"

In [70]:
pip install pandas openpyxl

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: openpyxl in /usr/local/lib/python3.12/dist-packages (3.1.5)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.12/dist-packages (from openpyxl) (2.0.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [71]:
import pandas as pd
import sqlite3

def xlsx_to_sqlite(excel_file_name, sqlite_db_name):
    conn = sqlite3.connect(sqlite_db_name)
    sheets = pd.read_excel(excel_file_name, sheet_name=None)

    for name, df in sheets.items():
        df.to_sql(name, conn, if_exists='replace', index=False)

    conn.close()

In [76]:
import sqlite3
import pandas as pd

def excel_to_sqlite(excel_path: str, sqlite_path: str, table_name: str = "salaries", if_exists: str = "replace"):
    df = pd.read_excel(excel_path)  # prend la 1ère feuille par défaut
    with sqlite3.connect(sqlite_path) as conn:
        df.to_sql(table_name, conn, index=False, if_exists=if_exists)

# Import
excel_to_sqlite("salaries.xlsx", "salaries.sqlite", table_name="salaries")

# Lecture
from sqlalchemy import create_engine
engine = create_engine("sqlite:///salaries.sqlite")
salaries = pd.read_sql_query("SELECT * FROM salaries", engine)
print(salaries)

        Unnamed: 0      Id     EmployeeName            JobTitle   BasePay  \
0            35637   35638    TSE SHIH LENG       ACCOUNT CLERK       614
1            34974   34975         LIEN LUM       ACCOUNT CLERK      1630
2            34975   34976       RACHEL LAU       ACCOUNT CLERK      1630
3            32035   32036   BARBARA BLOUNT       ACCOUNT CLERK   8681.58
4            31245   31246    ALISHA WILLIS       ACCOUNT CLERK  11247.02
...            ...     ...              ...                 ...       ...
148649      103333  103334  Mario R Yedidia  Youth Comm Advisor   13915.8
148650      138458  138459     Phimy Truong  Youth Comm Advisor  32417.42
148651       98074   98075    Phimy  Truong  Youth Comm Advisor  52433.88
148652       58842   58843    Mario Yedidia  Youth Comm Advisor  57544.73
148653       18778   18779      MYRON SULAK         ZOO CURATOR     43148

       OvertimePay  OtherPay  Benefits  TotalPay  TotalPayBenefits  Year  \
0                0         0      None    614.00            614.00  2011
1                0         0      None   1630.00           1630.00  2011
2                0         0      None   1630.00           1630.00  2011
3            69.82         0      None   8751.40           8751.40  2011
4                0         0      None  11247.02          11247.02  2011
...            ...       ...       ...       ...               ...   ...
148649           0   5296.91   5744.53  19212.71          24957.24  2013
148650           0   4048.49  15545.28  36465.91          52011.19  2014
148651           0         0   25297.5  52433.88          77731.38  2013
148652           0         0  28229.66  57544.73          85774.39  2012
148653           0  23538.56      None  66686.56          66686.56  2011

       Notes         Agency Status
0       None  San Francisco   None
1       None  San Francisco   None
2       None  San Francisco   None
3       None  San Francisco   None
4       None  San Francisco   None
...      ...            ...    ...
148649  None  San Francisco   None
148650  None  San Francisco     PT
148651  None  San Francisco   None
148652  None  San Francisco   None
148653  None  San Francisco   None

[148654 rows x 14 columns]

In [77]:
from sqlalchemy import create_engine
import pandas as pd

connexion = create_engine("sqlite:///salaries.sqlite")
salaries = pd.read_sql_query("select * from salaries", connexion)
display(salaries.head())

,Unnamed: 0,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,35637,35638,TSE SHIH LENG,ACCOUNT CLERK,614,0,0,None,614.00,614.00,2011,None,San Francisco,None
1,34974,34975,LIEN LUM,ACCOUNT CLERK,1630,0,0,None,1630.00,1630.00,2011,None,San Francisco,None
2,34975,34976,RACHEL LAU,ACCOUNT CLERK,1630,0,0,None,1630.00,1630.00,2011,None,San Francisco,None
3,32035,32036,BARBARA BLOUNT,ACCOUNT CLERK,8681.58,69.82,0,None,8751.40,8751.40,2011,None,San Francisco,None
4,31245,31246,ALISHA WILLIS,ACCOUNT CLERK,11247.02,0,0,None,11247.02,11247.02,2011,None,San Francisco,None

In [78]:
connexion=create_engine("sqlite:///salaries.sqlite")
salaries = pd.read_sql_query("select * from salaries", connexion)
print(salaries)

        Unnamed: 0      Id     EmployeeName            JobTitle   BasePay  \
0            35637   35638    TSE SHIH LENG       ACCOUNT CLERK       614
1            34974   34975         LIEN LUM       ACCOUNT CLERK      1630
2            34975   34976       RACHEL LAU       ACCOUNT CLERK      1630
3            32035   32036   BARBARA BLOUNT       ACCOUNT CLERK   8681.58
4            31245   31246    ALISHA WILLIS       ACCOUNT CLERK  11247.02
...            ...     ...              ...                 ...       ...
148649      103333  103334  Mario R Yedidia  Youth Comm Advisor   13915.8
148650      138458  138459     Phimy Truong  Youth Comm Advisor  32417.42
148651       98074   98075    Phimy  Truong  Youth Comm Advisor  52433.88
148652       58842   58843    Mario Yedidia  Youth Comm Advisor  57544.73
148653       18778   18779      MYRON SULAK         ZOO CURATOR     43148

       OvertimePay  OtherPay  Benefits  TotalPay  TotalPayBenefits  Year  \
0                0         0      None    614.00            614.00  2011
1                0         0      None   1630.00           1630.00  2011
2                0         0      None   1630.00           1630.00  2011
3            69.82         0      None   8751.40           8751.40  2011
4                0         0      None  11247.02          11247.02  2011
...            ...       ...       ...       ...               ...   ...
148649           0   5296.91   5744.53  19212.71          24957.24  2013
148650           0   4048.49  15545.28  36465.91          52011.19  2014
148651           0         0   25297.5  52433.88          77731.38  2013
148652           0         0  28229.66  57544.73          85774.39  2012
148653           0  23538.56      None  66686.56          66686.56  2011

       Notes         Agency Status
0       None  San Francisco   None
1       None  San Francisco   None
2       None  San Francisco   None
3       None  San Francisco   None
4       None  San Francisco   None
...      ...            ...    ...
148649  None  San Francisco   None
148650  None  San Francisco     PT
148651  None  San Francisco   None
148652  None  San Francisco   None
148653  None  San Francisco   None

[148654 rows x 14 columns]

In [79]:
# pour vérifier que vous avez bien répondu à l'exercice, soumettre cette cellule
# on utilise maj + Entrée
assert type(salaries) == pd.DataFrame
print("Bravo !")

Bravo !

# Les tris avec Pandas

Pour effectuer des tris, on utilise :
- `.sort_index()` pour le tri des index
- `.sort_values()` pour le tri des données
- `.rank()` affiche le rang des observations

Il peut y avoir plusieurs tris dans la même opération. Dans ce cas, on utilise des listes de colonnes :
```python
frame.sort_values(["col_1","col_2"])
```

**Exercice :**
    
Triez les données sur les salaires en se basant sur le BasePay et le JobTitle

In [80]:
salaries_sorted = salaries.sort_values(["JobTitle","BasePay"])

In [81]:
# pour vérifier que vous avez bien répondu à l'exercice, soumettre cette cellule
# on utilise maj + Entrée
assert salaries_sorted["JobTitle"].min() == salaries_sorted["JobTitle"].iloc[0]
print("Bravo !")

Bravo !

## Exportez des fichiers

La plupart des outils d'importation existent en exportation, on utilise :
```
frame.to_csv("fichier.csv")
```

**Exercice :**
    
Exportez les données salaries dans un fichier Excel

In [82]:
salaries_sorted.to_excel("salaries.xlsx")

# Les statistiques simples

Les Dataframe possèdent de nombreuses méthodes pour calculer des statistiques simples :
- `.sum(axis=0)` permet de faire une somme par colonne
- `.sum(axis=1)` permet de faire une somme par ligne
- `.min()` et `.max()` donnent le minimum par colonne
- `.idxmin()` et `.idxmax()` donnent l’index du minimum et du maximum
- `.describe()` affiche un tableau de statistiques descriptives par colonne
- `.corr()` pour calculer la corrélation entre les colonnes

**Exercice :**
    
Obtenir les moyennes et variances de la colonne `TotalPay` pour les données Salaries.

In [83]:
print(salaries["TotalPay"].mean())

74768.32197169265

In [84]:
salaries["TotalPay"].agg(["mean", "var"])

mean    7.476832e+04
var     2.551968e+09
Name: TotalPay, dtype: float64

# Le traitement des données manquantes

- Les données manquantes sont identifiées par `NaN`


- `.dropna()` permet de retirer les données manquantes dans un objet Series et l’ensemble d’une ligne dans le cas d’un DataFrame
- Pour éliminer par colonne, on utilise `.dropna(axis=1)`
- Remplacer toutes les données manquantes `.fillna(valeur)`

# Les jointures avec Pandas

On veut joindre des jeux de données en utilisant des clés (variables communes)

- `pd.merge()` permet de joindre deux DataFrame, on utilise comme options `on='key'`

- On peut utiliser comme option `how=`, on peut avoir :
    - `left` dans ce cas, on garde le jeu de données à gauche et pour les données de droite des valeurs manquantes sont ajoutées.
    - `outer`, on garde toutes les valeurs des deux jeux de données
    - ...

- On peut avoir plusieurs clés et faire une jointure sur les deux clés `on=['key1','key2']`

**Exercice :**
    
Joindre deux dataframes (credit1 et credit2). On commence par importer `credit1.txt`

In [85]:
credit1 = pd.read_table("credit2.txt")

In [88]:
credit_merged = pd.merge(credit1,credit2,on="Customer_ID")

KeyError: 'Customer_ID'

In [ ]:
# pour vérifier que vous avez bien répondu à l'exercice, soumettre cette cellule
# on utilise maj + Entrée
assert credit_merged.shape[1] == 31
print("Bravo !")

# Gestion des duplications

- On utilise `.duplicated()` ou `.drop_duplicates()` dans le cas où on désire effacer les lignes se répétant


- On peut se concentrer sur une seule variables en entrant directement le nom de la variable. Dans ce cas, c’est la première apparition qui compte. Si on veut prendre la dernière apparition, on utilise l’option `keep="last"`. On pourra avoir :
```python
frame1.drop_duplicates(["col_0","col_1"],keep="last")
```

# Les tableaux croisés avec Pandas

Les DataFrame possèdent des méthodes pour générer des tableaux croisés, notamment :
```python
frame1.pivot_table()
```
Cette méthode permet de gérer de nombreux cas avec des fonctions standards et sur mesure.

# L'utilisation de GroupBy sur des DataFrame

- `.groupby` permet de rassembler des observations en fonction d’une variable dite de groupe


- Par exemple, `frame.groupby('X').mean()` donnera les moyennes par groupes de `X`


- On peut aussi utiliser `.size()` pour connaître la taille des groupes et utiliser d’autres fonctions (`.sum()`)


- On peut effectuer de nombreuses opérations de traitement avec le groupby

**Exercice :**
    
- Données sur les salaires


- On utilise le `groupby()` pour rassembler les types d’emploi


- Et on calcule des statistiques pour chaque type


On peut utiliser la méthode `.agg()` avec par exemple `'mean'` comme paramètre

On utilise aussi fréquemment la méthode `.apply()` combinée à une fonction lambda

In [ ]:
salaries.groupby("JobTitle")["TotalPay"].mean().sort_values(ascending = False)